### ISSUE TITLE
Add Bunni class in `ape_api` 

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-multisig#1161]
- [x] Class should enable to:
  - Add liquidity
  - Remove liquidity
  - Stake
  - Unstake
  - Claim rewards

Considerations:

- [x] While claiming the rewards important visualising current discount of options provided by the [oracle](https://etherscan.io/address/0x9d43ccb1aD7E0081cC8A8F1fd54D16E54A637E30#readContract), and ideally assert in the scenario where the `multiplier` has malicious setting or alert in cli

- [x] Worth also updating the [script](https://github.com/Badger-Finance/badger-multisig/blob/main/scripts/badger/bribe_ecosystems.py) to allow posting incentives for bunni hh
