### ISSUE TITLE
Rebalance remBADGER dripper and manual drip of final month

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-multisig#1461]
The 2023 remBADGER [dripper](https://etherscan.io/address/0xC0D8fD5c722AF68437E7dFc095a980500dC0961D#tokentxns) is scheduled to finish on January 1st, 2024. Given the current held amount and the dripped amount per period it will end-up with a leftover. This outstanding amount must be clawed back. 

In addition, there will be an outstanding amount to be dripped to the vault throughout the month of January 2024 and until the completion of the program on February 3rd, 2024. The amounts per drip will be defined based on the outstanding total deposits at the end of the current dripper's schedule. The following [dashboard](https://dune.com/badgerdao/remBADGER) can be used to identify this amount.

**Comment by sajanrajdev** [comment]
# Drippers Status

[remBADGER 2023](https://etherscan.io/address/0xC0D8fD5c722AF68437E7dFc095a980500dC0961D#readContract):
- Period ended: Mon Jan 01 2024 00:00:00 GMT+0000
- Leftover: 3,396.2423896499238965 BADGER
- Outstanding Balance for Program: 20,704 BADGER

[Tree 2023](https://etherscan.io/address/0xA3Dc099D14722D0e25B3A904427377B4B2ab9fA4#tokentxns)
- Period ended: Mon Jan 01 2024 00:00:00 GMT+0000
- Leftover: 4,525.583460172501268392  BADGER
- Outstanding Balance for Program: 23,077 BADGER

## Action Plan
- [ ] Top-up Tree with Balance in a single transaction (claims are limited by emission schedule)
- [ ] Claw back dripper's balance and cancel their up-keeps
    - [ ] remBADGER 2023
    - [ ] Tree 2023
- [ ] Outstanding remBADGER deposits can be handled manually on signing day for the last month (20,704/5 = 4140.8)
    - [ ] Jan 4
    - [ ] Jan 11
    - [ ] Jan 18
    - [ ] Jan 25
    - [ ] Feb 1
- [ ] Estimate the outstanding tree emissions schedules and amounts for remBADGER and handle:
    - [ ] Post final emission schedule from TechOps
    - [ ] Transfer Tree Balance for remBADGER (Or all BADGER emissions)

**Comment by sajanrajdev** [comment]
## Outstanding Emission Schedule

The following [Query](https://dune.com/queries/3323501?category=decoded_project&namespace=badgerdao&contract=RewardsLogger&blockchains=ethereum&abi=UnlockScheduleSet) can be used to fetch all schedules completed for remBADGER.

An [analysis](https://docs.google.com/spreadsheets/d/1XjQmMqYozNBc8NekapFxVfiKvMhsEnCWYrtaK6eUH7Y/edit#gid=1189940560) on this shows that there is an outstanding schedule of 37591.57511 BADGERS to run from the end of the last one `1704067200` (Jan 1st, 2023) until the end of the remBADGER program (`1706918400`):
![Image](https://github.com/Badger-Finance/badger-multisig/assets/25463788/8e002d0e-da9a-4cac-8263-c04763b507ec)

Further analysis is required to understand the exact amount of BADGER that will be needed to fully cover the Tree requirements for the remBADGER program since, in the past, BADGER for the program was transferred along with BADGER used to cover emissions deficit without clear separation nor accounting. For the time being, it is safe to assume that the full outstanding amount covered by this schedule should be also missing from the tree and should be transferred over.

**Comment by sajanrajdev** [comment]
BADGER clawed back and transferred to trops, upkeep cancelled and emission schedule posted: https://etherscan.io/tx/0x8761f426f011183f73e158bbd90b705bef85a838746314d9ab2ec649908ccef2

**Comment by sajanrajdev** [comment]
LINK transferred back to UpkeepManager from KeeperReigstry: https://etherscan.io/tx/0x009c9a474667ebb869a95e3668e64b29825e403e61d97507684ab6e5799c6911
https://etherscan.io/tx/0xe8a4482ce0ccc65d2fac20b027de240b9a2b110f744adadcdb981ca6ae254c80

**Comment by sajanrajdev** [comment]
Tree and first remBADGER transfer: https://etherscan.io/tx/0x6bbc1afdad82b46d0086121d32a6c0e2fa48fd6c8cc30685332882155caecff5

**Comment by sajanrajdev** [comment]
It was found that both the Drippers ended up emitting their full balance. This means that the amount being dripped to remBADGER may be using an amount that is larger than required. Attention should be paid to the total outstanding from the [Dashboard](https://dune.com/badgerdao/remBADGER) and ensure that the last drip equals exactly the outstanding amount.

**Comment by sajanrajdev** [comment]
RemBADGER top-up: https://etherscan.io/tx/0xa483050e48eacc44dea274e8b98b5dc2498d7ca9467275efcc3a8fb3c275363f

**Comment by sajanrajdev** [comment]
RemBADGER top-up: https://etherscan.io/tx/0xcd6765f4c9782d45943ed92a0bdf081582118fb7a342610cf4a4e7acb676f72f

**Comment by sajanrajdev** [comment]
remBADGER top-up: https://etherscan.io/tx/0x76f839e339e11d5ec3b8252a8c2def00331daabd5f7633492c18652bcc10d3a0
